#= require "SimpleFunctionalTest"
#= require "SimpleConditionalFunctionalTest"
#= require "ComplexConditionsFunctionalTest"
#= require "FormFieldValidatorFunctionalTest"	
#= require "DelayedEventHandlingTest"
