{
	isFunction: isFunction
	isString: isString
	isArray: isArray
	isRegex: isRegex
	toArray: toArray
	elements: elements
	element: element
	observe: observe
	fire: fire
	bind: bind
	hasClass: hasClass
	show: show
	hide: hide
	toggle: toggle
	isVisible: isVisible
	addClass: addClass
	removeClass: removeClass
	toggleClass: toggleClass
	invoke: invoke
	each: each
	domReady: domReady
	extend: extend
	fieldValue: fieldValue
	trim: trim
	isInt: isInt
	isFloat: isFloat
	delayed: delayed
	cumulativeDelayed: cumulativeDelayed
}